update readme.md
4digitmwc/media-centre-articles pull request #2
Opened 2022-08-18 15:20 UTC by indekkusu-era

Updated a descriptive documentation on the Workflow of 4dm media centre article writing

2022-08-18 15:37 UTC, DannyPX requested changes
Probably not too important for now. But instead of saying click/clicking, use select/selecting.

2022-08-18 15:37 UTC, DannyPX commented on readme.md
> +Then click **Commit Changes**.
This workflow doesn't actually require VSC then. Is VSC really recommended then?
Would prefer to have 2 sections one with Notion and one with VSC then. (Would also be nice to show how to export in Notion)

2022-08-18 15:37 UTC, DannyPX commented on readme.md
> +In order to review a Pull Request, you click into a Pull Request URL and go to "Files changed", Click "Review Changes" and add your comment
```suggestion
In order to review a Pull Request from a different author, you click into a Pull Request URL and go to "Files changed", Click "Review Changes" and add your comment
```

2022-08-18 15:37 UTC, DannyPX commented on readme.md
> +Normally, it's like ranking a map, you need two BNs to approve your map in order to be ranked. This one you need at least two contributors to Approve your pull request in order to merge into the main
Maybe add that you can request from specific people as well?

2022-08-18 15:37 UTC, DannyPX commented on readme.md
> +Then click `Add File > Upload Files`
```suggestion
Then click **Add File** and then **Upload Files** in the dropdown menu.
```

2022-08-18 15:37 UTC, DannyPX commented on readme.md
> +This is a documentation for 4 Digit MWC Media Centre Workflow via Github
```suggestion
This is a documentation for 4 Digit MWC Media Centre Workflow via Github.
```

2022-08-18 15:37 UTC, DannyPX commented on readme.md
> +Create a separate branch by clicking at the branch icon. The branch name must be in format `yourname/<updates>` (example below)
```suggestion
Create a separate branch by clicking at the branch icon. The branch name must be in format `yourname/<updates>` (example below).
```

2022-08-18 15:37 UTC, DannyPX commented on readme.md
> +After finishing your Article Markdown, go to the folder (stories/interviews/opinions) and upload the file based on category you wrote
```suggestion
After finishing your Article Markdown, go to the folder (stories/interviews/opinions) and upload the file based on category you wrote.
```

2022-08-18 15:37 UTC, DannyPX commented on readme.md
> +For example, if you create a new story, you upload the story by clicking `stories` folder
```suggestion
For example, if you create a new story, you upload the story by clicking `stories` folder.
```

2022-08-18 15:37 UTC, DannyPX commented on readme.md
> +Then you drop your markdown file or choose from your directory and write a **Commit Changes**
```suggestion
Then you drop your markdown file or choose from your directory and write a commit message.
```

2022-08-18 15:37 UTC, DannyPX commented on readme.md
> +After you added new articles or update them, you need to do **Pull Request** for articles to be reviewed. You start by clicking **Pull Requests**
```suggestion
After you added new articles or update them, you need to do **Pull Request** for articles to be reviewed. You start by clicking **Pull Requests**.
```

2022-08-18 15:37 UTC, DannyPX commented on readme.md
> +Then, click **New Pull Request**, then change the `compare:` to your branch (below for example)
```suggestion
Then, click **New Pull Request**, then change the `compare:` to your branch (below for example).
```

2022-08-18 15:37 UTC, DannyPX commented on readme.md
> +Click **Create Pull Request** and it will bring you to this page
```suggestion
Click **Create Pull Request** and it will bring you to this page.
```

2022-08-18 15:37 UTC, DannyPX commented on readme.md
> +In order to review a Pull Request, you click into a Pull Request URL and go to "Files changed", Click "Review Changes" and add your comment
```suggestion
In order to review a Pull Request, you click into a Pull Request URL and go to "Files changed", Click "Review Changes" and add your comment.
```

2022-08-18 15:37 UTC, DannyPX commented on readme.md
> +Then click `Add File > Upload Files`
Would check consistency on this throughout the whole article.

2022-08-18 15:39 UTC, DannyPX commented on readme.md
> +In order to review a Pull Request, you click into a Pull Request URL and go to "Files changed", Click "Review Changes" and add your comment
```suggestion
In order to review a Pull Request, you click into a Pull Request URL and go to "Files changed", click "Review Changes" and add your comment
```

2022-08-19 14:45 UTC, indekkusu-era commented on readme.md
> +Then click **Commit Changes**.
VSC is just another option to edit markdown, and I am planning to provide resources or write a brief documentation for these

2022-08-19 14:53 UTC, indekkusu-era commented on readme.md
> +Normally, it's like ranking a map, you need two BNs to approve your map in order to be ranked. This one you need at least two contributors to Approve your pull request in order to merge into the main
uhh can you elaborate more of this ? from what I understand, you want me to add the documentation about review request feature on github right ?

2022-08-19 15:17 UTC, DannyPX commented on readme.md
> +Normally, it's like ranking a map, you need two BNs to approve your map in order to be ranked. This one you need at least two contributors to Approve your pull request in order to merge into the main
Yes, since its more likely (in this case) that we actually review something that is requested.

2022-08-19 15:18 UTC, DannyPX commented on readme.md
> +Then click **Commit Changes**.
Will it be in this readme or something separate?

2022-08-19 15:50 UTC, indekkusu-era commented on readme.md
> +Then click **Commit Changes**.
planning to be included in readme

2022-08-19 15:50 UTC, indekkusu-era commented on readme.md
> +Normally, it's like ranking a map, you need two BNs to approve your map in order to be ranked. This one you need at least two contributors to Approve your pull request in order to merge into the main
alright

2022-08-20 15:25 UTC, indekkusu-era commented on readme.md
> +Then click **Commit Changes**.
done

2022-08-20 15:25 UTC, indekkusu-era commented on readme.md
> +Normally, it's like ranking a map, you need two BNs to approve your map in order to be ranked. This one you need at least two contributors to Approve your pull request in order to merge into the main
done

2022-08-20 17:58 UTC, polytetralhx approved these changes
hi, seems all good to go on my end, reverse MTGL

2022-08-24 10:11 UTC, merged